CREATE DATABASE IF NOT EXISTS database_06_mdh;
USE database_06_mdh;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(32) NOT NULL
);

